#!/usr/bin/env node
/* -*- Mode:js */
/* vim: set expandtab ts=4 sw=4: */
/*
 * You may redistribute this program and/or modify it under the terms of
 * the GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

const Walker = require('./walker');
const Config = require('./config');

const main = () => {
    const lastArg = process.argv[process.argv.length-1];
    if (!/^v[0-9]+\.[0-9a-f\.]{20}[a-z0-9]{52}\.k$/.test(lastArg)) {
        console.log("usage: getpeersof v17.0000.0000.1234.5678." +
            "713kfhl1udkg9xrz6EXAMPLEz2xg880vgyspzxmvm1gfqdl4wmr0.k");
        return;
    }
    Walker.peersOf(Config.walkerMagic, lastArg, (err, ret, peers) => {
        if (err) {
            console.log("Error: " + err);
            return;
        }
        console.log(JSON.stringify(ret, null, '  '));
        console.log(JSON.stringify(peers, null, '  '));
    });
};
main();
